export const en = {
  nav: { brand: 'Mathematics', langRu: 'RU', langKz: 'KZ', langEn: 'EN' },
  catalog: {
    title: 'Educational Programs',
    desc: 'Choose the course you need to download the installer and purchase a license key.',
    loading: 'Loading catalog...',
    empty: 'Catalog is empty',
    emptyDesc: 'Programs coming soon.',
    btnDownload: 'Download',
    btnBuy: 'Buy',
    btnMore: 'Learn more',
    btnHide: 'Hide',
    private: 'Private',
    corporate: 'Corporate',
    perMonth: 'mo.',
    comingSoon: 'soon',
  },
  buy: {
    title: 'Purchase License',
    privateTab: 'Private',
    corporateTab: 'Corporate',
    nameLabel: 'Your name',
    periodLabel: 'Subscription period',
    totalLabel: 'Total',
    btnPay: 'Proceed to payment',
    redirect: 'Redirecting...',
    secureNote: 'Secure payment via Lemon Squeezy. Card details are not shared with the seller.',
  },
  footer: { copyright: '© 2026 Educational Platform' },
};