export const kz = {
  nav: { brand: 'Математика', langRu: 'RU', langKz: 'KZ', langEn: 'EN' },
  catalog: {
    title: 'Білім беру бағдарламалары',
    desc: 'Орнатушыны жүктеп алу және лицензия кілтін сатып алу үшін қажетті курсты таңдаңыз.',
    loading: 'Каталог жүктелуде...',
    empty: 'Каталог бос',
    emptyDesc: 'Бағдарламалар жақында пайда болады.',
    btnDownload: 'Жүктеу',
    btnBuy: 'Сатып алу',
    btnMore: 'Толығырақ',
    btnHide: 'Жасыру',
    private: 'Жеке',
    corporate: 'Корпоративтік',
    perMonth: 'ай',
    comingSoon: 'жақында',
  },
  buy: {
    title: 'Лицензияны сатып алу',
    privateTab: 'Жеке',
    corporateTab: 'Корпоративтік',
    nameLabel: 'Сіздің атыңыз',
    periodLabel: 'Жазылу мерзімі',
    totalLabel: 'Барлығы',
    btnPay: 'Төлеуге өту',
    redirect: 'Қайта бағыттау...',
    secureNote: 'Lemon Squeezy арқылы қауіпсіз төлем. Карта деректері сатушыға берілмейді.',
  },
  footer: { copyright: '© 2026 Білім беру платформасы' },
};