export const ru = {
  nav: { brand: 'Математика', langRu: 'RU', langKz: 'KZ', langEn: 'EN' },
  catalog: {
    title: 'Образовательные программы',
    desc: 'Выберите нужный курс для скачивания установщика и приобретения лицензионного ключа.',
    loading: 'Загрузка каталога...',
    empty: 'Каталог пуст',
    emptyDesc: 'Программы скоро появятся.',
    btnDownload: 'Скачать',
    btnBuy: 'Купить',
    btnMore: 'Подробнее',
    btnHide: 'Свернуть',
    private: 'Частная',
    corporate: 'Корпоративная',
    perMonth: 'мес.',
    comingSoon: 'скоро',
  },
  buy: {
    title: 'Покупка лицензии',
    privateTab: 'Частная',
    corporateTab: 'Корпоративная',
    nameLabel: 'Ваше имя',
    periodLabel: 'Период подписки',
    totalLabel: 'Итого',
    btnPay: 'Перейти к оплате',
    redirect: 'Перенаправление...',
    secureNote: 'Безопасная оплата через Lemon Squeezy. Данные карты не передаются продавцу.',
  },
  footer: { copyright: '© 2026 Образовательная платформа' },
};